# Homework 1. MNIST 데이터셋을 활용해 다중 분류 수행하기
### 과목코드: [2150085101] (2150034001/2150085101)
### 팀명: [4조]
### 팀장: [장진영] (학번과 이름)
### 팀원: [강현준] (학번과 이름)
### 팀원: [이시호] (학번과 이름)

#### 문제. 아래의 `코드`를 완성하고, 그에 대한 `분석`을 작성하시오.

1. (코드) MNIST 데이터셋 받기
   - (분석) 데이터셋에 대해 분석하기

In [5]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

In [6]:
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

2. (코드) 데이터셋을 train / validation / test set 으로 분할하기
   - (분석) 데이터셋을 분할한 방식에 대해 설명하고, 해당 분할 방식을 수행한 이유에 대해 설명하기

train set 과 validation set 과 test set의 optimal한 비율은 정해져 있지 않지만

대부분의 경우 train set 60 ~ 80% validation set 10 ~ 20% test set 10 ~ 20%의 비율로 분할을 합니다.

MNIST 데이터 셋의 경우 7만개의 sample중 1만개는 test sample 이므로

60000개를 train set으로

10000개를 test set으로 하였으며

train set 60000개중에 10000개를 validation set으로 분할하였습니다.

참고자료

https://www.v7labs.com/blog/train-validation-test-set

https://encord.com/blog/train-val-test-split/

In [7]:
X, y = mnist['data'], mnist['target']
y = y.astype(np.uint8)
X_train, X_valid, X_test ,y_train ,y_valid ,y_test = X[:50000], X[50000:60000],X[60000:],y[:50000], y[50000:60000],y[60000:]
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train, y_train, test_size=0.1, random_state=42)

3. (코드) 특성 스케일링을 이용한 데이터셋 전처리하기
   - (분석) 스케일링을 수행한 방식에 대해 설명하고, 해당 스케일링을 수행한 이유에 대해 설명하기

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train_split)
X_val_scaled = scaler.transform(X_val_split)
X_test_scaled = scaler.transform(X_test)

4. (코드) 모델 선택하기
   - (분석) 머신러닝 모델의 후보군들에 대해 설명하고, 후보군들 중 특정 모델이 대표 모델로 선택된 이유에 대해 설명하기

머신러닝 모델중 다층퍼셉트론 모델은 비선형적인 데이터에 대해 학습을 할 수 있기 때문에 이미지,음성,텍스트 등 여러 분야에 활용되는데 해당 모델과 수:업시간에 배운 확률적 경사 하강 모델(SGD) 랜덤포레스트 모델(Randomforeset),결정트리 모델(decisionTree)과 비교하였습니다.
참고자료 https://mozenworld.tistory.com/entry/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EB%AA%A8%EB%8D%B8-%EC%86%8C%EA%B0%9C-6-%EB%8B%A4%EC%B8%B5-%ED%8D%BC%EC%85%89%ED%8A%B8%EB%A1%A0-Multilayer-Perceptron

In [9]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train_scaled, y_train_split)

SGDClassifier(random_state=42)

In [10]:
from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier(random_state=42)
forest_clf.fit(X_train_scaled, y_train_split)

RandomForestClassifier(random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier
decision_clf = DecisionTreeClassifier(random_state=42)
decision_clf.fit(X_train_scaled, y_train_split)

DecisionTreeClassifier(random_state=42)

In [12]:
from sklearn.neural_network import MLPClassifier
multilayerperceptron_clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
multilayerperceptron_clf.fit(X_train_scaled,y_train_split)

MLPClassifier(max_iter=500, random_state=42)

In [14]:
from sklearn.model_selection import cross_val_score
y_acc_sgd = cross_val_score(sgd_clf, X_train_scaled, y_train_split, cv=3, scoring="accuracy")
y_acc_forest = cross_val_score(forest_clf, X_train_scaled, y_train_split, cv=3, scoring="accuracy")
y_acc_decision = cross_val_score(decision_clf, X_train_scaled, y_train_split, cv=3, scoring="accuracy")
y_acc_multilayer = cross_val_score(multilayerperceptron_clf,X_train_scaled,y_train_split, cv=3, scoring="accuracy")

In [21]:
print(f"[SGD] Accuray: {y_acc_sgd}")
print(f"[RF] Accuray: {y_acc_forest}")
print(f"[DT] Accuray: {y_acc_decision}")
print(f"[MULT] Accuray: {y_acc_multilayer}")

[SGD] Accuray: [0.8998     0.90173333 0.9064    ]
[RF] Accuray: [0.95906667 0.96566667 0.96193333]
[DT] Accuray: [0.8442     0.85533333 0.85093333]
[MULT] Accuray: [0.96786667 0.97313333 0.96486667]


In [19]:
sgd_clf.score(X_test,y_test)
forest_clf.score(X_test,y_test)
decision_clf.score(X_test,y_test)
multilayerperceptron_clf.score(X_test,y_test)
print(f"[SGD]  score: {sgd_clf.score(X_test,y_test)}")
print(f"[RF]   score: {forest_clf.score(X_test,y_test)}")
print(f"[DT]   score: {decision_clf.score(X_test,y_test)}")
print(f"[MULT] score: {multilayerperceptron_clf.score(X_test,y_test)}")

[SGD]  score: 0.7708
[RF]   score: 0.9633
[DT]   score: 0.7313
[MULT] score: 0.9764


정확도와 score을 보았을때 다층 퍼셉트론 모델이 다른 모델보다 높은 것을 확인 할 수 있습니다.



5. (코드) 성능 평가하기
   - (분석) 최종적으로 학습된 모델을 이용해 test set 에 대한 성능을 정리하고, 이를 분석하기

In [23]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_train_pred = cross_val_predict(multilayerperceptron_clf, X_train_scaled, y_train_split, cv=3)
mtx_cf = confusion_matrix(y_train_split, y_train_pred)

In [24]:
print('Confution Matrix: \n', mtx_cf)

print('Number of Samples: \t  ',    f'{mtx_cf.sum():5d}',    f'({mtx_cf.sum() / mtx_cf.sum() * 100:6.2f}%)')
print('Number of Negative Labels:', f'{mtx_cf[0].sum():5d}', f'({mtx_cf[0].sum() / mtx_cf.sum() * 100:6.2f}%)')
print('Number of Positive Labels:', f'{mtx_cf[1].sum():5d}', f'({mtx_cf[1].sum() / mtx_cf.sum() * 100:6.2f}%)')

Confution Matrix: 
 [[4340    3    8    6    4   25   17    4   13   15]
 [   1 5024   19   10    9    0    2   12   19    1]
 [  14   21 4304   30   24    5   11   34   26    5]
 [   3    3   37 4407    4   52    4   13   39   22]
 [   5    9   14    2 4278    3   14   13    7   50]
 [   7    8    6   45    7 3941   10    7   35   23]
 [  22    9    7    2   16   39 4328    3   16    1]
 [   2   12   32   15   15   10    1 4542   15   35]
 [  18   26   18   44   13   41   14    7 4128   40]
 [  11    5    2   21   40   24    2   38   16 4296]]
Number of Samples: 	   45000 (100.00%)
Number of Negative Labels:  4435 (  9.86%)
Number of Positive Labels:  5097 ( 11.33%)


In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
TN = mtx_cf[0, 0]
FP = mtx_cf[0, 1]
FN = mtx_cf[1, 0]
TP = mtx_cf[1, 1]

func_acc = lambda mtx_cf: (mtx_cf[0, 0] + mtx_cf[1, 1]) / (mtx_cf[0, 0] + mtx_cf[0, 1] + mtx_cf[1, 0] + mtx_cf[1, 1])
func_pre = lambda mtx_cf: (mtx_cf[1, 1]) / (mtx_cf[0, 1] + mtx_cf[1, 1])
func_rec = lambda mtx_cf: (mtx_cf[1, 1]) / (mtx_cf[1, 0] + mtx_cf[1, 1])
func_spe = lambda mtx_cf: (mtx_cf[0, 0]) / (mtx_cf[0, 0] + mtx_cf[0, 1])
func_f1 = lambda precision, recall: 2 * (precision * recall) / (precision + recall)

acc = accuracy_score(y_train_split,y_train_pred)
prec = precision_score(y_train_split,y_train_pred,average='weighted')
recall = recall_score(y_train_split,y_train_pred,average='weighted')
f1 = f1_score(y_train_split,y_train_pred,average='weighted')

acc_ = func_acc(mtx_cf)
prec_ = func_pre(mtx_cf)
recall_ = func_rec(mtx_cf)
f1_ = func_f1(prec_, recall_)

spe_ = func_spe(mtx_cf)


print(f"Metrics:      Function ~ Confusion")
print(f"Accuracy:\t{acc:.4f} ~ {acc_:.4f}")
print(f"Precision:\t{prec:.4f} ~ {prec_:.4f}")
print(f"Recall:\t\t{recall:.4f} ~ {recall_:.4f}")
print(f"F1:\t\t{f1:.4f} - {f1_:.4f}")

Metrics:      Function ~ Confusion
Accuracy:	0.9686 ~ 0.9996
Precision:	0.9686 ~ 0.9994
Recall:		0.9686 ~ 0.9998
F1:		0.9686 - 0.9996


작성중...

6. (코드) 에러 분석하기
   - (분석) 최종적으로 학습된 모델의 에러를 분석하기
   - (분석) `5. 성능 평가하기` 의 분석과 연관지어 에러를 분석하고 해결책을 제안하기

참고자료